<%@ Page Title="" Language="vb" AutoEventWireup="false" MasterPageFile="~/SideBarMaster.master" CodeBehind="CaseStudy.aspx.vb" Inherits="Agripedia.CaseStudy" %>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <form runat="server">
        <div class="container-fluid">
            <div class="container">
                <div class="row" style="margin-top: 2.8%">

                    <div class="col-md-10">
                        <div id="content-core">
                            <div id="MiddleColumn_internal">
                                <a name="section-1"></a>
                                <h3>Cost Effective Shade Net House</h3>
                                <p>
                                    <strong>
                                        <img alt="Shri Jaganath" src="http://vikaspedia.in/agriculture/best-practices/shri-jaganath" title="Shri Jaganath" class="image-inline"></strong>
                                </p>
                                <p><strong>Profile</strong></p>
                                <p>
                                    <strong>Shri Jagnnath Gangaram Tayade</strong><br>
                                    A/P Ladsavangi, Taluq &amp; District Aurangabada, Maharashtra<br>
                                    (Mobile : 09421313616)
                                </p>
                                <p>
                                    <strong>Age:</strong> 50 years<br>
                                    <strong>Education: </strong>10 std<br>
                                    <strong>Landholding: </strong>7.2 ha<br>
                                    <strong>Farming experience:</strong> 27 Years<br>
                                    <strong>Crops grown:</strong> Cotton, maize, sweet&nbsp; orange seed&nbsp; production of&nbsp; capsicum, tomato&nbsp; and water melon
                                        <br>
                                    <strong>Livestock:</strong> Cow and buffaloes
                                </p>
                                <strong>Description of innovation</strong>
                                <p>Shade net house was developed by Shri. Jagnnath Tayade&nbsp; from locally available iron material. Total height of the shade net&nbsp; house is 6m from center place, Length is 36 m and width is 24 m.&nbsp; The shade net house requires wire ropes. Here the obstacles within&nbsp; shade net are negligible which helps for smooth intercultural&nbsp; operations and easy movement of labour as compared to&nbsp; recommended one.</p>
                                <p>
                                    <img alt="cost effective shade net house" src="http://vikaspedia.in/agriculture/best-practices/cost-effective-shade-net-house" title="cost effective shade net house" class="image-inline">
                                </p>
                                <strong>Practical utility of innovation</strong>
                                <p>This type of shade net house is suitable for growing heighted crops like capsicum, tomato, chili, etc. This shade net house sustains wind speed up to 80 km/hr and is economically viable as the total cost required to construct is Rs 60000 which become 30% less than the recommended technology and rain water is drained easily due to doom shape structure. At present 15 farmers had adopted this type of structure on 0.10 ha each and are taking seed production programme of capsicum and tomato</p>
                                <p><strong><i>Source : <a class="ext-link-icon" href="http://amefound.org/" target="_blank" title="AME Foundation (External website that opens in new window)">AME Foundation </a></i></strong></p>
                                <a name="section-2"></a>
                                <h3>Vermicomposting brings better yields and returns - A small farmer shows the way</h3>
                                <p align="center"><strong></strong></p>
                                <p>This is the case of a small farmer who chose to be different from the typical resource-&nbsp; poor farmers struggling to make a living in the degraded drylands. His deep ‘love for life’ has not only earned him a decent living, but more importantly, it has inspired many other farmers to emulate him.</p>
                                <p>Chandranna, a young farmer, is known as ‘Nursery Chandranna’ before and ‘Vermicompost Chandranna’ now. He has earned Rs. 1.4 lakhs from the sale of vermicompost and earthworms in three years. It has now become a fairytale in the region where the average annual earnings for a small farmer like him does not exceed Rs. 15000.</p>
                                <p>An ideal village, an unfavourable setting, Chandranna lives in Tumkurlahalli, a village with 650 households in Molakalmuru Taluk of Chitradurga District of Karnataka. The village consists predominantly the backward communities – 410 SC families, 100 muslims and 100 lingayat families with a population of 3800. The village has about 3322 ha. of which 15% is dryland and 3.5% is under bore well irrigation. The remaining 2695 ha. (81.5%) is common land that includes wasteland, common grazing land and the ‘reserve forest’ where only shrubs and bushes are seen, occasionally. The terrain, in general, has shallow red sandy soils. With boulders scattered all over, it is not an ideal village for remunerative farming. With less than 500 mm. average annual rainfall, the farmers are forced into a gamble with groundnut cultivation, the only cash crop grown year after year. Over 30 years of monocropping, with groundnut and groundnut alone, has resulted in the yield levels declining to a dismal 8 q./ha. Though agriculture is hardly a lucrative proposition, majority of the people still depend on agriculture and wage labour for their livelihoods. Naturally, the village witnesses migration of men folk for most part of the year.</p>
                                <p><strong>Small farmer with big hopes</strong></p>
                                <p>In a village where agriculture hardly throws up surprises, Chandranna’s case demonstrates that keen interest and self-belief can make agriculture a dependable enterprise. For, it is not a story of overnight success but one of a systematic effort to utilize opportunities offered to the farmers in the village from a variety of agencies.</p>
                                <p>Coming from a poor farming family, Chandranna has inherited 3 acres of dryland of which one acre is uncultivable wasteland. Wage labour, hence, was more important a source of livelihood for the family than agriculture in the two acre land. His parents wanted their only son to study. It was however not possible for him to go beyond the pre-university level, owing to poverty. He was forced to return and join his parents in farming. In the Karnataka Watershed Development (KAWAD) project, with AME Foundation as a resource agency, Chandranna joined a Self-Help Group (SHG).</p>
                                <strong>The triggering point</strong>
                                <p>In 2000, Chandranna participated in a training on nursery raising at BAIF Institute of Rural Development, Karnataka (BIRD K), in Tiptur. But, he was more curious to know about vermicomposting, a parallel training session being organised for another group of farmers at the same time. He would join the group whenever possible. He got excited about rearing earthworms and preparing vermicompost.</p>
                                <p>On his return from nursery training, his group was given an opportunity to raise a nursery of 15,000 seedlings. The task was entrusted to Chandranna. Chandranna raised nursery for three consecutive years starting from the year 2000. His nursery was rated the best in the watershed project in 2003 and Chandranna became popular as ‘Nursery Chandranna’.</p>
                                <p>A modest beginning and a spectacular surge His curiosity about vermicomposting continued. With the little knowledge that he had gained during the training, he tried multiplying local species of earthworms in coconut shells. However, they did not survive.</p>
                                <p>In 2003, Chandranna built four vermicompost pits of size 6x3x3 cu.ft. with the support of KAWAD project. He didn’t know how to use the pits, though. A staff of GUARD then brought 2 kg. of earthworms which costed Chandranna Rs. 300. With the 2 kg. earthworms, he produced 20 q. vermicompost which he applied to his 2 acres of ragi crop. Growing ragi itself was an experiment in Tumkarlahalli as no one had grown ragi in the village before. He got 14 q. from 2 acres.</p>
                                <p>In 2004, he applied 6 q. of good quality vermicompost and 2 tractor loads of FYM (2 tons) along with a bag of DAP to 2 acres. This time he cultivated groundnut and obtained an yield of 20 bags weighing 9 q. of groundnuts.</p>
                                <p>Visiting tree-based farming systems, interacting with farmers who had been successful in composting and vermicomposting helped Chandranna in getting a broader idea about sustainable agriculture. He learnt more about vermicomposting with his visit to another progressive farmer in nearby village, B G Kere.</p>
                                <p>In the year 2005, Chandranna applied 6 q. vermicompost to one acre PTD plot along with sets of combination of practices like summer ploughing, seed treatment with bio agents (Rhizobium and Trichoderma), application of Gypsum (50 kg.), using a higher than normal seed rate (45 kg.), growing intercrops and border crops. The yield went up to 13 bags from one acre giving him 6.5 q. groundnuts. It was the highest yield recorded by a farmer from one acre in the last four years of AMEF’s work in the region. What was remarkable was the weight of each bag, which ranged between 50 and 60 kg. While Chandranna’s 25 bags weighed 13 q., his neighbour Tippeswamy’s 40 bags, weighed only 13 q. The trader buying the produce could not believe this. Infact the traders forced Chandranna to pour the contents out of the bag to make sure the bag did not contain stones. It was unusual that a bag of groundnut pods weighed more than 50 kgs. The uniform pod maturity and proper filling had improved the quality of groundnuts significantly.</p>
                                <p><strong>Vermicomposting, a lucrative enterprise</strong></p>
                                <p>
                                    <img alt="vermicomposting" src="http://vikaspedia.in/agriculture/best-practices/vermicomposting" title="vermicomposting" class="image-inline">
                                </p>
                                <p>Chandranna did not stop at producing vermicompost and applying it to his two acre land. He started selling both the earthworms and the vermicompost from 2004. In 2004, Chandranna sold 124 kg. earthworms at Rs. 150 per kg. earning Rs. 18,600. He earned another Rs. 7500 by selling 15 q. vermicompost at Rs. 500/q. On the whole, he earned around Rs. 26,100.</p>
                                <p>Inspired by an income higher than the one from groundnut, he intensified production and sale of worms and compost in 2005. In the process, he learned some lessons the hard way. He once packed 30 kg. of earthworms in soil culture for selling, which died before the deal was over. Later, he started selling worms packed in cow dung. When the watershed project, in its concluding year, offered more vermicompost pits to large number of farmers, the demand for earthworms further increased. He could earn Rs. 41,700 from sale of 278 kg. worms (at Rs. 150/kg.) and Rs. 11,500 from the sale of 23 q. compost at Rs. 500/q. That brought him a total of Rs. 53,200 in 2005. He further increased the number of vermicomposting pits. He started looking out for more crop residues and agricultural wastes. The four pongemia trees in his field, the biomass from the trees along the canal and the dry eucalyptus leaves provided raw material for his vermicompost pits. Realising the need for cowdung for vermicomposting, Chandranna started maintaining a pair of bullocks, a cow and 20 hens. The returns are on the rise, consistently. In the year 2006, in an year that witnessed unprecedented drought-like situation that was not seen in the last 50 years, Chandranna still managed to earn Rs. 58,750 by way of selling 285 kg. worms and 32 q. of vermicompost. His total earning since 2003 has been Rs. 1,38,050. The actual earnings could be much more. The Rs. 1.4 lakhs he earned is recorded in the account he has maintained by offering receipts. His ‘customers’ are mostly the SHGs and farmers coming from many NGOs in Bellary, Chitradurga, Bagalkot and Bijapur districts, who insist on bills. There are individual farmers buying compost or worms without asking for bills, in which case no records are available on the transactions. Now, he is offering a special price of Rs.100/kg. for SHGs, whereas others have to pay Rs.150. The nearby customers get an additional after-sales service from Chandranna. Chandranna visits his customers farms and if the survival of worms is not satisfactory, he provides some more worms, free of cost.</p>
                                <p><strong>The beacon of hope for the hopeless</strong></p>
                                <p>The popular name ‘Nursery Chandranna’ has now changed to ‘Vermicompost Chandranna’. A modest mud house is now getting extended with cement walls along with the increasing number of vermicomposting pits in the backyard. He has already inspired many farmers in his village to try out alternative farming practices in general and take up vermicomposting in particular. The self motivated farmers like Chandranna are just the kind of catalysts the NGOs look for in converting small successes into mass movements. It is just the right kind of urge many resource poor farmers need to overcome the limitations and defy the odds.</p>
                                <p><strong><i>Source : <a class="ext-link-icon" href="http://amefound.org/" target="_blank" title="AME Foundation (External website that opens in new window)">AME Foundation</a></i></strong></p>
                                <a name="section-3"></a>
                                <h3>Daal Mill improves nutritional security in Mentapalli</h3>
                                <p>
                                    <img alt="Dall mill" src="http://vikaspedia.in/agriculture/best-practices/dall-mill" title="Dall mill" class="image-inline">
                                </p>
                                <p>Mentapalli in Mahbubnagar district of Andhra Pradesh is like any other village of the semiarid India. It gets around 650 mm rainfall that is distributed erratically from mid June to September. The village is dominated by small and marginal farmers who cultivate their parched lands for a single season. During the dry periods, farmers migrate to far off places, in search of employment.</p>
                                <p>Pigeonpea is an important crop in this area, along with sorghum and maize. Bacterial wilt of pigeonpea is a serious soil-borne disease resulting in severe crop loss. With the interventions of the livelihoods program by ICRISAT (International Crops Research Institute for the Semi-Arid Tropics), farmers are now able to reap some harvests by growing wilt-tolerant pigeonpea variety <i>Asha. </i>It tolerates wilt to a great extent and yields 20 to 30 per cent than the local variety.</p>
                                <p>The traditional practice after harvesting pigeonpea, was to split the produce by hand&nbsp; operated grinding stones. This operation was generally done by men. Ever since the men started migrating from the village, this practice almost ceased to continue. On the contrary, this tiny village producing a lot of pigeonpea, started selling it in the market for a paltry Rs 12 –14 a kg and bought <i>daal </i>for a higher price at Rs 22 a kg., for domestic consumption.</p>
                                <p>The ICRISAT Watershed Team decided to break the typical ‘selling cheap and buying costly’ syndrome in Mentapalli and had discussions with the villagers. The villagers agreed to the proposal of processing the pigeonpea within the village to make enough <i>daal, </i>at least, for the domestic consumption. The Society for Development of Drought Prone Areas (SDDPA), an NGO implementing the program in Mentapalli watershed, motivated and mobilized the women’s self help group. Accordingly, a simple <i>daal </i>mill was installed in the village. Following installation, farmers were trained in handling the machine.</p>
                                <p>The SHG mobilised money to pay towards power consumption. It fixed the cost of milling a kilogram of <i>daal. </i>Thus, the villagers could get their pigeonpea milled at a reasonable cost besides getting grain husk as nutritive fodder.</p>
                                <p>However, the <i>daal </i>milled in the village could not fetch good price in the market, as it did not have the shine and the color. Therefore, the milled <i>daal </i>had to be used for domestic consumption only. As <i>Asha </i>was known for its better cooking quality and bold grains, it was the preferred option, particularly by the women.</p>
                                <p>Now the mill is working in full swing turning the Mentapalli pigeonpea in to <i>daal </i>(with almost 90% recovery) and bringing smiles on villagers’ faces. The women are happy as they are able to cook and taste what their family cultivates. They expressed that now they have access to increased nutrition at a lesser price, as <i>daal </i>is the cheapest source of protein.</p>
                                <strong>Success and spread</strong>
                                <p>Three factors have been responsible for the success of the daal-mill. Firstly, the operation of the mill was very simple and was similar to that of handling a typical floor mill, seen in any village. Secondly, the method of splitting pigeonpea was compatible to the villagers’ indigenous practice of soaking the pigeonpea overnight and sun-drying for 2-3 days before milling. Lastly, the simple <i>daal </i>mill operated on single-phase power supply, suitable for Mentapalli which has no three phase power supply.</p>
                                <p>The success of the daal-mill has spread to the neighbouring villages. People from other villages are getting their pigeonpea milled in Mentapalli.</p>
                                <p>Now the SHG in Mentapalli is planning to buy one Mill for the village, as the project installed daal mill is to be shifted to other villages of the project. Enthused by the outcome at Mentapalli, the idea is being successfully tried out in other places of Kurnool district, where pigeonpea is grown abundantly.</p>
                                <p><strong>Sreenath Dixit, </strong>Central Research Institute for Dryland Agriculture, Hyderabad, India</p>
                                <p><strong>SP Wani and Ch Ravinder Reddy, </strong>International Crops Research Institute for the Semi-Arid Tropics, Patancheru, Andhra Pradesh,  India</p>
                                <p><strong><i><strong><i>Source : <a class="ext-link-icon" href="http://leisaindia.org/" target="_blank" title="LEISA India (External website that opens in new window)">LEISA India</a></i></strong>, Vol 6-3</i></strong></p>
                                <a name="section-4"></a>
                                <h3><strong>A garden by children changing the face of the village</strong></h3>
                                <p align="center"><strong></strong></p>
                                <p>
                                    <img alt="pic1" src="http://vikaspedia.in/agriculture/best-practices/pic1" title="pic1" class="image-inline">
                                </p>
                                <p>Baliaghati of West Medinipur is a tribal village inhabited by people belonging to very low income group with lack of basic facilities like health and nutrition. NPMS, a local organization has been fighting for long to change the scenario. Since 2006, DRCSC&nbsp; started working with NPMS involving children in the age group of 12~15 on Ecology and Natural Resource related learning and experimentation activities.</p>
                                <p>Baliaghati is an area, where flood and drought, the two most destructive and atrocious forms of nature, are a common factor and the poorest of people living here have no option but to accept these vagaries of nature as part and parcel of their lives. Vegetables have never been a part of their staple diet. In June 2008 about 200 packets of vegetable seeds were distributed among 30 children. 18 of them could raise garden within their homestead.</p>
                                <p>
                                    <img alt="pic2" src="http://vikaspedia.in/agriculture/best-practices/pic2" title="pic2" class="image-inline">
                                </p>
                                <p>Initiatives of others in the group were washed out by the flood waters. The packets contained the seeds of swamp cabbage, snake gourd, ridged gourd, bottle gourd, sweet potato, cowpea, yam bean, soybean, cucumber, bitter gourd, okra, Indian spinach, tarukala etc. They were reluctant to eat some of these vegetables as they had never seen them before. Later, NPMS took the initiative to cook and serve these less known vegetables in a bid to popularize them. Compost and vermicompost prepared by the children themselves were used for enriching the soil. On an average each of them received about 150 kg of vegetable within 3~4 months. The children kept a detailed record of the activities undertaken, changes observed, processes undergone, incidence and nature of pest attack, lifecycle of the plants, rate of germination and the quantity &amp; quality of produce. These records gave the children an idea of the science behind it. Parents also showed considerable interest in the entire activity.</p>
                                <p>Apart from the eco-group children and their parents, now the other villagers are also getting an opportunity to eat these vegetables as the children have shared the surplus with them as a part of their awareness campaign so that all villagers could know the benefits of raising a garden in their backyards.</p>
                                <p>The activity was supported by Indienhilfe.</p>
                                <p><strong><i><strong><i>Source : <a class="ext-link-icon" href="http://www.drcsc.org/archive.html#NEW" target="_blank" title="DRCSC (External website that opens in new window)">DRCSC news,</a></i></strong>, Issue No. 3</i></strong><strong><i> </i></strong></p>
                                <a name="section-5"></a>
                                <h3>Small is beautiful</h3>
                                <p>
                                    <img alt="vermi unit" src="http://vikaspedia.in/agriculture/best-practices/vermi-unit" title="vermi unit" class="image-inline">
                                </p>
                                <p>Rakhi Turi, a housewife of a slum in Bolpur town is also the member of Bholapukur 1 small saving and credit group. Her husband Bikash Turi is a rickshaw puller. His monthly earning is Rs. 1650 which is not at all enough for their 5 headed family. This Schedule caste family is also listed in BPL list of the Government. Rakhi was in search of work, but could not find any. At that time DRCSC intervened there with the vermicompost making venture supported by Innovative Challenge Fund, KUSP. Rakhi Turi and her group showed their interest to this venture.</p>
                                <p>The project aimed to form 5 groups with 15 women members in each group. These groups would be collecting the vegetables wastes from the bolpur markets and make vermicompost commercially. The women of Bholapukur 1 group decided to construct pits to make vermicompost on the land of an organization in Jamuboni called 'Support'. The women members got training on how to make vermicompost. The males of the families also extended their help to collect vegetable wastes from markets. The women started collecting straws, cow dung etc. They started to make vermicompost with the high quality vermis. They all decided the name for their product also 'Basundhara Vermi Compost'. The total production for the first month was 400 kg from 2 vats. Now the time was to take initiative for selling their product. It was decided that the market price will be Rs. 10 per kg. After sale Rs. 1000 will be saved in the bank account to make pits in future. The rest will be distributed equally among the members.</p>
                                <p>Rakhi Turi could spend 1-2 hrs a day after her regular household work. She earned Rs. 200 in the first month. Her husband also had some extra earning by renting his rickshaw for collecting raw materials and campaigning for this project. Rakhi Turi was very happy as she was able to earn some extra income by spending her extra time and acclaimed that the business will made much larger by them in future.</p>
                                <p><strong><i><strong><i><strong><i>Source : <a class="ext-link-icon" href="http://www.drcsc.org/archive.html#NEW" target="_blank" title="DRCSC (External website that opens in new window)">DRCSC newsletter,</a></i></strong></i></strong>, Issue 6</i></strong></p>
                                <a name="section-6"></a>
                                <h3>An innovation that generates revenue for rural women</h3>
                                <p>
                                    <br>
                                    <img alt="K.vivekanandan" src="http://vikaspedia.in/agriculture/best-practices/k-vivekanandan" title="K.vivekanandan" class="image-inline">
                                </p>
                                <p>Mr. K. Vivekanandan of Coimbatore (Tamil Nadu) invested Rs.8 lakh and created a 3 HP pin pulverizer for grinding chilli and coriander. "The machine is an ideal revenue generator for rural women who are interested in increasing their domestic income,” says Mr. Vivekanandan.</p>
                                <p>Most of the existing machines to grind chilli and coriander require high installation costs, and use a lot of power making it unsuitable for rural areas, where power supply may also be undependable.</p>
                                <p><strong>Challenges faced</strong></p>
                                <p>Mr. Vivekanandan thought he solved 90 per cent of the grinding problem when he developed the machine, and manufactured nearly 100 of them. But to his dismay he found that only 20 pieces found buyers. Some of the buyers returned the machine, because the chilli and coriander did not pass through the filter screen, and created too much dust while grinding.</p>
                                <p>Work came to a standstill, and did not resume for almost a year.</p>
                                <p>Mr. Vivekanandan came to know about Villgro (an organization that supports rural entrepreneurs) and he approached them for guidance. The staff at Villgro tapped different resources to work on this problem. Technical expertise first assisted Mr. Vivekanandan in producing a 1 HP, single phase machine, because the machine could not initially run at a speed on 3 HP. (In rural areas the preference is for a one- HP, single-phase machine due to voltage fluctuation).</p>
                                <p>After several trials they identified the problem of chilli and coriander getting stuck on the screen was not because of their high fibre content, but due to the speed of the rotor. Accordingly, the weight of the machine was reduced, its wall thickness, size, and diameter of the stator and rotor altered to suit rural application.</p>
                                <p><strong>Cost </strong></p>
                                <p>Mr. Vivekanandan brought down the cost of the machine to cater to rural needs by focusing on the types and amount of materials used. Each unit is priced at Rs. 11,500 (with motor).</p>
                                <p><strong>For more information readers can contact:</strong></p>
                                <p>Mr. K. Vivekanandan, M/s Vivega Engineering Works, New No: 116-118, Sathy   Road, R. K. Puram, Ganapathy, Coimbatore - 641 006. Mobile No: 94437-21341.</p>
                                <p><strong><i>Source : <a class="ext-link-icon" href="http://www.hinduonnet.com/seta/2009/11/26/stories/2009112650251400.htm" target="_blank" title="The Hindu (External website that opens in new window)">A innovation that generates revenue for women, Science &amp; Technology column, The Hindu</a></i></strong></p>
                            </div>
                        </div>

                    </div>
                </div>

            </div>

        </div>
    </form>
</asp:Content>
