'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Fruits
    
    '''<summary>
    '''Carrot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Carrot As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Tomato control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Tomato As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Cabbage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cabbage As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Cucumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cucumber As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Chilli control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Chilli As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Parsley control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Parsley As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Beans control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Beans As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Dill control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dill As Global.System.Web.UI.WebControls.Button
End Class
