'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class OtherVeggie
    
    '''<summary>
    '''cauliflower control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cauliflower As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''fenugreek control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fenugreek As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''amaranthus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents amaranthus As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''cowpea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cowpea As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''bhendi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bhendi As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''capsicum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents capsicum As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''pea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pea As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''rajma control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rajma As Global.System.Web.UI.WebControls.Button
End Class
